version: '3'
services:
  app:
    build: .
    environment:
      - PORT=8080
    ports:
      - 8080:8080
  ui:
    build: ui
    environment:
      - PORT=8000
    ports:
      - 8000:8000

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:

