version: '3'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - RUNNING_IN_CONTAINER=true
    ports:
      - 8080:8080
    depends_on:
      - influxdb
      - mqtt

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      -  ./config/mosquitto:/mosquitto/config

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./config/influxdb/config.yml:/etc/influxdb2/config.yml
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:

